### ISSUE TITLE
module 'fish_audio_sdk' has no attribute 'ReferenceAudio'

### ISSUE THREAD

**Issue by cryang0205** [fishaudio/fish-audio-python#3]
Hi,
I used the sample code from the GitHub (https://github.com/fishaudio/fish-audio-python) and using ReferenceAudio in TTSRequest, but an error occurs (**module 'fish_audio_sdk' has no attribute 'ReferenceAudio'**). 

Could you help me identify what might be going wrong?

```
TTSRequest(
    text="Hello, world!",
    references=[
        ReferenceAudio(
            audio=audio_file.read(),
            text="reference audio text",
        )
    ],
)
```

**Comment by abersheeran** [comment]
Use `from fish_audio_sdk import TTSRequest, ReferenceAudio`
