### ISSUE TITLE
Unable to Use SDK for TTS

### ISSUE THREAD

**Issue by talongao** [fishaudio/fish-audio-python#5]
I am encountering issues while attempting to use the SDK for Text-to-Speech (TTS). Despite following the provided documentation and examples, I am unable to successfully generate speech from text.

## Steps to Reproduce:

1. **Setup Environment:**
   - Operating System: Ubuntu 20.04
   - SDK Version: 2024.10.22
   - Programming Language: Python 3.10.15

2. **Code Snippet:**
```python
from fish_audio_sdk import Session, TTSRequest

def main():
    f = None
    if result_path is not None:
        f = open(result_path, "wb")
    for chunk in self.session.tts(
        TTSRequest(text=text, reference_id=voice_id, format=audio_format)
    ):
        if f is not None:
            f.write(chunk)
            f.flush()
        elif result_array is not None:
            result_array.extend(chunk)

if __name__ == "__main__":
    main()
```
3. Expected Behavior:
- The SDK should successfully synthesize the provided text into speech and return an audio stream.

4. Actual Behavior:
- raise Exception: TypeError('Type is not msgpack serializable: TTSRequest')

**Comment by talongao** [comment]
It does not work in version 2024.11.28.

**Comment by abersheeran** [comment]
https://github.com/aviramha/ormsgpack/issues/311

**Comment by talongao** [comment]
Thanks

**Comment by talongao** [comment]
The ormsgpack is still at version 1.6.0. If you are using pydantic >= 2.10.0, you can temporarily replace TTSRequest with a dict.It's work.
```python
for chunk in self.session.tts(dict(text=text, reference_id=voice_id, format=audio_format)):
    f.write(chunk)
    f.flush()
```
